### ISSUE TITLE
Add Lv50 Statpool

### ISSUE THREAD

**Issue by rabidsheep** [gh4ever101/gh4ever101.github.io#2]
because pvp scales to lv50, maybe adding an additional row to the attack and defense tables to display stats as they appear at lv50 would be good. i don't fully understand how stats work in this game yet, but at lv50 a single thunder bingo on tobi-kadachi raises its thunder attack by ~31 points, while at lv99 it raises it by ~54 points.

**Comment by gh4ever101** [comment]
Great tip! I didn't realize PVP scales levels to level 50 (shows how much I actually play PVP, lol). Generally it might be a good idea to just use the stats for level 50 then. Ideally we would be able to calculate them on the fly depending on base stats and what level the user sets the monstie at, but I also don't fully understand how stats work in this game.

**Comment by gh4ever101** [comment]
Fixed in latest commit.
